// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPFZ88IghXGs718XotrMDrfEJno79O9UU',
    appId: '1:575840013918:web:7db94308ec2c505801eecf',
    messagingSenderId: '575840013918',
    projectId: 'smart-canteen-d2e6e',
    authDomain: 'smart-canteen-d2e6e.firebaseapp.com',
    storageBucket: 'smart-canteen-d2e6e.firebasestorage.app',
    measurementId: 'G-DXZXDJWX6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Jd0JaOPnaqdfBDdDWFg9MT9eON-Nc24',
    appId: '1:575840013918:android:065c153de7ae030901eecf',
    messagingSenderId: '575840013918',
    projectId: 'smart-canteen-d2e6e',
    storageBucket: 'smart-canteen-d2e6e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrK0pjJ1bl8WoRy-PcgzcmyaAlI0Ha7ug',
    appId: '1:575840013918:ios:fd780994cf31a6cf01eecf',
    messagingSenderId: '575840013918',
    projectId: 'smart-canteen-d2e6e',
    storageBucket: 'smart-canteen-d2e6e.firebasestorage.app',
    iosBundleId: 'com.example.smartCanteenApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrK0pjJ1bl8WoRy-PcgzcmyaAlI0Ha7ug',
    appId: '1:575840013918:ios:fd780994cf31a6cf01eecf',
    messagingSenderId: '575840013918',
    projectId: 'smart-canteen-d2e6e',
    storageBucket: 'smart-canteen-d2e6e.firebasestorage.app',
    iosBundleId: 'com.example.smartCanteenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPFZ88IghXGs718XotrMDrfEJno79O9UU',
    appId: '1:575840013918:web:d2d5899b4592837101eecf',
    messagingSenderId: '575840013918',
    projectId: 'smart-canteen-d2e6e',
    authDomain: 'smart-canteen-d2e6e.firebaseapp.com',
    storageBucket: 'smart-canteen-d2e6e.firebasestorage.app',
    measurementId: 'G-66V56TSYPS',
  );
}
